    image: node:latest

    stages:
      - build
      - lint
      - test

    cache:
      paths:
        - node_modules/

    install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/
    eslint_linting:
      stage: lint
      script: npm run pretest
    jest testing:
      stage: test
      script: npm run test  